# Generated by Django 4.0.4 on 2022-05-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
