# Generated by Django 4.0.4 on 2022-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
