# Generated by Django 4.0.4 on 2022-05-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0003_alter_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='questions_answered',
            field=models.ManyToManyField(blank=True, to='jeopardy.question'),
        ),
    ]
